projects:
    backend:
        type: deeptracy-python:2.7
        strategy: requirement_file
        unimportant: false
        config:
            path: src/backend
            requirement: requirements.txt
