projects:
    backend:
        type: deeptracy-python:2.7
        strategy: requirement_file
        unimportant: false
        config:
            path: src/backend
            requirement: requirements.txt
    frontend:
        type: deeptracy-node:8
        strategy: npm_install
        unimportant: false
        config:
            path: src/frontend
