plugins:

    bbvalabsci/gitsec-git-secrets:
        unimportant: yes
        options:
            prohibited:
                dni:
                    value: "[0-9]{6,9}[a-zA-Z]"
                    type: regex
    bbvalabsci/gitsec-api-key-detect:
    bbvalabsci/gitsec-git-hound:
    bbvalabsci/gitsec-gittyleaks:
    bbvalabsci/gitsec-trufflehog:
